spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.223.196.38:3306/stock?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

server:
  port: 8080